server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true

logging:
  level:
    com.example.demo: DEBUG
    com.zaxxer.hikari: DEBUG
    org.flywaydb: DEBUG
    org.hsqldb: DEBUG

spring:
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      schema: PUBLIC
      username: SA
      password:
  flyway:
    enabled: true
    baselineOnMigrate: true
